codestates-seb/seb40_main_015

.idea/.gitignore
backend/dongnebook/src/main/java/com/dongnebook/domain/book/book.java
backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/Book.java
backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/BookState.java
backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/Money.java
backend/dongnebook/src/main/java/com/dongnebook/domain/book/ui/BookController.java
backend/dongnebook/src/main/java/com/dongnebook/domain/member/controller/member.java
backend/dongnebook/src/main/java/com/dongnebook/domain/member/ui/member.java
backend/dongnebook/src/main/java/com/dongnebook/domain/model/Location.java

[BE] Feat : 책 엔티티 생성

---

backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/Book.java
backend/dongnebook/src/main/java/com/dongnebook/global/error/ErrorResponse.java
backend/dongnebook/src/main/java/com/dongnebook/global/error/GlobalExceptionHandler.java
backend/dongnebook/src/main/java/com/dongnebook/global/error/exception/BusinessException.java
backend/dongnebook/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java

- 모든 예외를 처리할 ControllerAdvice 추가
- 비즈니스 로직을 처리할 공통 예외 생성
- Error Code를 enum으로 관리
- 공통 Error Response 생성
- Book Entity @Lob 추가

[BE] Feat : 공통예외처리

---

backend/dongnebook/build.gradle
backend/dongnebook/src/main/java/com/dongnebook/domain/book/application/BookService.java
backend/dongnebook/src/main/java/com/dongnebook/domain/book/domain/Book.java
backend/dongnebook/src/main/java/com/dongnebook/domain/book/dto/Request/BookRegisterRequest.java
backend/dongnebook/src/main/java/com/dongnebook/domain/book/repository/BookRepository.java
backend/dongnebook/src/main/java/com/dongnebook/domain/book/ui/BookController.java
backend/dongnebook/src/main/java/com/dongnebook/domain/member/domain/Member.java
backend/dongnebook/src/main/java/com/dongnebook/domain/member/exception/LocationNotCreatedYetException.java
backend/dongnebook/src/main/java/com/dongnebook/domain/member/repository/MemberRepository.java
backend/dongnebook/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
backend/dongnebook/src/main/java/com/dongnebook/global/error/ErrorResponse.java
backend/dongnebook/src/main/java/com/dongnebook/global/error/GlobalExceptionHandler.java
backend/dongnebook/src/main/java/com/dongnebook/global/error/exception/BusinessException.java
backend/dongnebook/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java

[BE] Feat : 책 등록 기능 추가

---

frontend/src/components/common/TabLists.tsx
frontend/src/hooks/useTabs.ts
frontend/src/pages/MerchantPage.tsx

-useTabs에 curTab이 이제는 탭이름만 출력됩니다.
-TabLists 타입선언 부분을 간결해 보이게 정리 해봤습니다

[FE] feat : useTabs 와 TabLists 일부 수정

---

backend/build.gradle
backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
backend/src/main/java/com/dongnebook/domain/book/domain/BookState.java
backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookRegisterRequest.java
backend/src/main/java/com/dongnebook/domain/book/dto/response/BookDetailResponse.java
backend/src/main/java/com/dongnebook/domain/book/dto/response/BookResponse.java
backend/src/main/java/com/dongnebook/domain/book/repository/BookCommandRepository.java
backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
backend/src/main/java/com/dongnebook/domain/member/dto/Request/MemberLoginRequest.java
backend/src/main/java/com/dongnebook/domain/member/dto/Request/MemberRegisterRequest.java
backend/src/main/java/com/dongnebook/domain/member/dto/response/BookDetailMemberResponse.java
backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
backend/src/main/java/com/dongnebook/domain/model/BaseTimeEntity.java
backend/src/main/java/com/dongnebook/global/config/QueryDslConfig.java
backend/src/main/resources/application.yml
backend/src/test/java/com/dongnebook/domain/test.java

- 책 상세조회 기능 추가
- BaseTimeEntity 추가
- 상세조회에 대여시간은 아직 안추가
- 더미데이터용 회원가입로직 추가

[BE] Feat : 책 상세조회 기능 추가

---

frontend/src/components/common/Title.tsx

[FE] feat : Title 로고 추가

---

frontend/src/components/History/LendBookLists.tsx
frontend/src/components/History/RentBookLists.tsx
frontend/src/components/History/RentStatusButton.tsx
frontend/src/components/History/SortButton.tsx
frontend/src/components/common/TabLists.tsx
frontend/src/pages/HistoryPage.tsx

[FE] feat : 레이아웃 변경

---

backend/src/main/java/com/dongnebook/DongnebookApplication.java
backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
backend/src/main/java/com/dongnebook/domain/book/dto/Request/SectorBookCountRequest.java
backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSectorCountResponse.java
backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
backend/src/main/java/com/dongnebook/domain/model/Location.java
backend/src/main/resources/application.yml
backend/src/test/java/com/dongnebook/Location/locationTest.java

- 그냥 도 단위로 계산했습니다.
- 조건에 맞는 책들을 모두 가져와서 어플리케이션 레벨에서 가공했습니다.

[BE] Feat : 도서 검색 - 지도에 구획별 책 갯수를 뿌려준다. v1

---

frontend/src/components/Login/LoginForm.tsx
frontend/src/components/Login/Logo.tsx
frontend/src/components/SignUp/Bubble.tsx
frontend/src/components/SignUp/SignUpForm.tsx
frontend/src/pages/LoginPage.tsx
frontend/src/pages/SignupPage.tsx

[FE] design : 로그인, 회원가입 페이지 레이아웃 조정

---

backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
backend/src/main/java/com/dongnebook/domain/rental/dto/Request/RentalRegisterRequest.java
backend/src/main/java/com/dongnebook/domain/rental/dto/Response/RentalResponse.java
backend/src/main/java/com/dongnebook/domain/rental/exception/CanNotRentMyBookException.java
backend/src/main/java/com/dongnebook/domain/rental/exception/NotCancelableException.java
backend/src/main/java/com/dongnebook/domain/rental/exception/RentalNotFoundException.java
backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
backend/src/main/resources/application.yml

- Rental 도메인 : 대여 취소 기능 구현 (취소 주체 고려 안 함)
- Rental 도메인 : 대여하기 기능 본인이 대여 못하도록 로직 추가
- Rental 도메인 : 대여하기 기능 도서 상태 변경 로직 추가
- Book 도메인 : 도서상태 변경 메서드 추가
- 대여하기 및 대여 취소 수행 시, 발생할 수 있는 예외사항 처리용 코드 및 로직 추가
- application.yml 파일 서버 포트 설정 초기화

[BE] feat: 대여 취소 기능 구현

---

backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
backend/src/main/java/com/dongnebook/domain/rental/exception/CanNotCancelRentalException.java
backend/src/main/java/com/dongnebook/domain/rental/exception/CanNotReceiveRentalException.java
backend/src/main/java/com/dongnebook/domain/rental/exception/CanNotReturnRentalException.java
backend/src/main/java/com/dongnebook/domain/rental/exception/NotReceivableException.java
backend/src/main/java/com/dongnebook/domain/rental/exception/NotReturnableException.java
backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java

- Rental 도메인 : 도더 수령 기능 구현
- Rental 도메인 : Rental 엔티티 id 필드 변수의 strategy애트리뷰트 값 GenerationType.IDENTITY로 변경
- Rental 도메인 : Rental 엔티티 book객체의 연관 관계 '일대일 관계'에서 '다대일 관계'로 변경
- Rental 관련 에러 코드 및 에러처리 메서드 추가

[BE] Feat: 도서 수령 기능 구현

---

frontend/src/components/LoginOnly/index.tsx
frontend/src/components/Notice/NoticeIcon.tsx
frontend/src/components/Notice/NoticeItem.tsx
frontend/src/pages/NoticePage.tsx

* 알림페이지 구현
* LoginOnly 페이지에 알림 아이콘 띄움
* 알림 아이콘 클릭시 알림페이지 이동

[FE] Feat: 알림 페이지 구현

---

backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java

- Rental 도메인 : 토큰값 사용하여 유저 구분하도록 코드 리팩토링

[BE] Refactor: Rental 도메인 토큰값 사용

---

frontend/src/components/Map/Map.tsx
frontend/src/components/Map/Search.tsx
frontend/src/components/Map/dummy.ts
frontend/src/pages/BooksSearchPage.tsx

* 검색창 입력 구현
: 책 검색시 기존 상인마커 및 커스텀 레이아웃 삭제
* 상인 커스텀 레이아웃 클릭 이벤트
: 상인 커스텀 레이아웃 클릭시, 클릭한 값으로 state 업데이트되게 구현
* 리스트 구현
: data가 있을시 지도 하단에 리스트 생성되게 구현
: 리스트 animation 구현
* 현재위치 버튼 기능 구현
: 현재위치 버튼 클릭시 user의 현재 위치로 재설정

[FE] Feat: 검색창 엔터 이벤트, 커스텀 오버레이 클릭 이벤트, 리스트 상태 및 애니메이션 구현, 현재 위치 버튼 기능 구현

---

backend/src/main/java/com/dongnebook/global/config/security/auth/filter/JwtAuthenticationFilter.java

-2차 배포 전 로그인 API에서 Response body에 담긴 내용이 API 명세서와 일치하도록 수정했습니다 (memberid, 아이디, 닉네임 포함)

[BE] Refactor: 로그인 API Response 내용 수정

---

frontend/src/api/test.tsx
frontend/src/components/Map/BookLists.tsx
frontend/src/components/Map/Map.tsx
frontend/src/components/Map/MerchantLists.tsx
frontend/src/components/Map/dummy.ts
frontend/src/pages/BooksSearchPage.tsx

* 검색 페이지 - 섹터당 상인 위치 api 통신 테스트 진행했습니다

[FE] Feat : API 통신 테스트

---

backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookSearchCondition.java
backend/src/main/java/com/dongnebook/domain/model/Location.java
backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java

[BE] Refactor : 지도 가로세로 1km 로 수정

---

frontend/src/components/LoginOnly/LoginCheckElements.tsx
frontend/src/components/Map/BookLists.tsx
frontend/src/components/Map/Map.tsx
frontend/src/components/Map/Search.tsx
frontend/src/components/Map/dummy.ts
frontend/src/pages/BooksSearchPage.tsx

* 책 검색 - 책 상태 리스트 구현(책 이름, 대여상태, 상인)
* 커스텀 오버레이 - 상인 수에 따른 오버레이 크기 변경(한자리수, 두자리수, 세자리수 기준)
* 검색창 - 빈칸 상태로 검색 시, 현재 위치 주변 상인 정보 불러오기 로직 추가
* 지도 레벨 - 1~5까지 확대/축소 기능 추가(기본 레벨은 5로 변경)

[FE] Feat: 지도 검색 - 책 상태 리스트 구현, 커스텀 오버레이 상인 수에 따른 크기 변경, 검색창 로직 추가, 지도 확대 축소 기능 수정

---

frontend/src/components/Map/BookLists.tsx
frontend/src/components/Map/Map.tsx
frontend/src/components/Map/MerchantLists.tsx
frontend/src/components/common/NavTemp.tsx
frontend/src/pages/ChatsPage.tsx

* 지도 검색 - 주변 도서 대여 상태 안내 구현(대여가능, 예약가능, 대여/예약 불가 색상별 표시)
* navbar css 수정 - 프론트엔드 모여서 이야기한 내용으로 수정 
* 채팅 페이지 - "현재 페이지는 서비스 준비중입니다"라고 기재

[FE] Feat: 지도 검색 주변 도서 대여 상태 표시 , navbar css 수정, 채팅 페이지 서비스 준비중 표시 

---

backend/build.gradle
backend/restart-h2.sh
backend/restart.sh
backend/src/main/resources/application-rds-createdb.yml
backend/src/main/resources/application-rds.yml

- RDS(MySQL) 사용하는 application 설정 파일 2개 추가 (ddl-auto: none, create)
- 백그라운드 수행 자동화 스크립트 파일 추가
- build.gragle에 mariaDB 사용 관련 dependency 추가

[BE] Feat: RDS 사용 설정 추가

---

backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookSearchCondition.java
backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
backend/src/main/java/com/dongnebook/domain/member/dto/request/MemberEditRequest.java
backend/src/main/java/com/dongnebook/domain/member/dto/request/MerchantSearchRequest.java
backend/src/main/java/com/dongnebook/domain/member/dto/response/BookDetailMemberResponse.java
backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberDetailResponse.java
backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberLoginResponse.java
backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
backend/src/main/java/com/dongnebook/domain/model/Location.java

- 로그인 응답에 memberId 추가
- 책 상세 조회에 merchantId 추가

Refactor : 로그인 응답에 memberId 추가

---

backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
backend/src/main/java/com/dongnebook/domain/rental/repository/RentalRepository.java
backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java

- Rental 도메인 : 빌린 책 조회 기능 구현
- Rental 도메인 : 빌려준 책 조회 API, 빌린 책 조회 API - 로그인한 사용자의 토큰으로부터 사용자 id값을 받아오도록 수정

[BE] Feat: 빌린 책 조회 기능 구현

---

backend/src/main/resources/application-rds.yml

- RDS 연동 설정 변경: ddl-auto: none -> ddl-auto: update

[BE] Infra: RDS 연동 설정 변경

---

backend/build.gradle
backend/src/main/java/com/dongnebook/domain/Image/application/AwsS3Service.java
backend/src/main/java/com/dongnebook/domain/Image/application/ImageUploadService.java
backend/src/main/java/com/dongnebook/domain/Image/dto/ImageUploadRequest.java
backend/src/main/java/com/dongnebook/domain/Image/exception/UploadFailed.java
backend/src/main/java/com/dongnebook/domain/Image/ui/ImageUploadController.java
backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
backend/src/main/java/com/dongnebook/domain/book/dto/Request/BookRegisterRequest.java
backend/src/main/java/com/dongnebook/domain/book/dto/response/BookSimpleResponse.java
backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
backend/src/main/java/com/dongnebook/domain/model/Location.java
backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
backend/src/main/resources/application-rds-createdb.yml
backend/src/main/resources/application-rds.yml
backend/src/main/resources/application.yml

- 지도 섹터수를 자유롭게 변경 가능하도록 했습니다. 예) 5*5, 4*4
- 사진 업로드를 하고 url를 반환하는 api가 추가됐습니다.
- 상인 정보의 책목록을 반환하는 api가 추가됐습니다

[BE] Feat : 지도 섹터 수 변경하는 기능, 사진 업로드 api 추가

---

backend/src/main/java/com/dongnebook/DongnebookApplication.java
backend/src/main/java/com/dongnebook/global/HelloController.java

- 메인 메서드에 한국 시간으로 설정하는 코드 추가
- 기본 주소에 현재 시간 확인하는 API 코드 추가

[BE] Feat: 한국시간설정 코드 추가

---

frontend/src/api/mypage.ts
frontend/src/components/Member/BookStatus.tsx
frontend/src/components/Member/PickBookList.tsx
frontend/src/components/Merchant/ButtonStatus.tsx
frontend/src/components/common/Modal.tsx
frontend/src/pages/ProfileEditPage.tsx
frontend/src/pages/ProfilePage.tsx

* 마이페이지 - 찜목록 query 구현 완료(찜하기 api 명세서 수정 완료)
* 내정보수정하기페이지 / 모달창 - css 수정
* 내정보수정하기페이지 - 프로필 이미지 등록

[FE] Feat: 마이페이지 - 찜목록 query 구현 완료, 내정보수정하기페이지 및 모달창 css 수정

---

backend/restart-h2.sh
backend/restart.sh

- 자동화 스크립트에 설정 코드 추가로 출력 로그 파일에 기록되도록 설정

[BE] Infra: EC2 서버 출력 로그 파일화

---

backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
backend/src/main/java/com/dongnebook/domain/rental/repository/RentalRepository.java
backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
backend/src/main/java/com/dongnebook/domain/reservation/application/ReservationService.java
backend/src/main/java/com/dongnebook/domain/reservation/domain/Reservation.java
backend/src/main/java/com/dongnebook/domain/reservation/domain/ReservationState.java
backend/src/main/java/com/dongnebook/domain/reservation/exception/CanNotChangeReservationStateException.java
backend/src/main/java/com/dongnebook/domain/reservation/exception/CanNotReservationBookStateException.java
backend/src/main/java/com/dongnebook/domain/reservation/exception/CanNotReservationPersonException.java
backend/src/main/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepository.java
backend/src/main/java/com/dongnebook/domain/reservation/repository/ReservationRepository.java
backend/src/main/java/com/dongnebook/domain/reservation/ui/ReservationsController.java
backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java

- Reservation 도메인 : 예약하기 기능 구현
- Reservation 도메인 : 예약하기 기능 관련 기본 구성 파일들 구현
- Reservation 도메인 : 예약하기 기능 관련 예외 처리 기능 구현
- Rental 도메인 : 대여도서 반납 시, 예약하기 기능 관련 로직 추가
- Rental 도메인 : controller 부분 리팩토링 (변수명 수정: merchant -> customer)

[BE] Feat: 도서 예약하기 기능 구현

---

backend/src/main/java/com/dongnebook/domain/reservation/application/ReservationService.java
backend/src/main/java/com/dongnebook/domain/reservation/dto/response/ReservationInfoResponse.java
backend/src/main/java/com/dongnebook/domain/reservation/dto/response/ReservationResponse.java
backend/src/main/java/com/dongnebook/domain/reservation/repository/ReservationQueryRepository.java
backend/src/main/java/com/dongnebook/domain/reservation/ui/ReservationsController.java
backend/src/main/java/com/dongnebook/domain/review/application/ReviewService.java
backend/src/main/java/com/dongnebook/domain/review/dto/response/ReviewResponse.java
backend/src/main/java/com/dongnebook/domain/review/repository/ReviewQueryRepository.java
backend/src/main/java/com/dongnebook/domain/review/ui/ReviewController.java

- Review 도메인: 리뷰 조회 기능 구현 (무한스크롤 동작 포함)
- Reservation 도메인: 잘못된 폴더명 변경 (dto.request -> dto.response)

[BE] Feat: 리뷰조회 기능 구현

---

backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
backend/src/main/java/com/dongnebook/domain/book/dto/response/BookResponse.java
backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
backend/src/main/java/com/dongnebook/domain/book/ui/BookController.java
backend/src/main/java/com/dongnebook/domain/chat/dto/request/RoomRequest.java
backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberLoginResponse.java
backend/src/main/resources/application.yml

[BE] Refactor : RoomRequest 기본생성자 제거

---

backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java

Feat : CORS 설정 추가

---

backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java

- 대여중인 책이 있을때는 회원정보 수정을 못하게 변경

[BE] Feat : 대여중인 책이 있을때는 회원정보 수정을 못하게 변경

---

backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
backend/src/main/java/com/dongnebook/domain/chat/application/ChatService.java
backend/src/main/java/com/dongnebook/domain/chat/application/RoomService.java
backend/src/main/java/com/dongnebook/domain/chat/domain/ChatRoom.java
backend/src/main/java/com/dongnebook/domain/chat/dto/request/RoomRequest.java
backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatResponse.java
backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatRoomResponse.java
backend/src/main/java/com/dongnebook/domain/chat/dto/response/LastChatResponse.java
backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java
backend/src/main/java/com/dongnebook/global/config/WebSocketConfig.java
backend/src/main/java/com/dongnebook/global/config/security/auth/SecurityConfiguration.java
backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
backend/src/main/resources/application-rds-createdb.yml
backend/src/main/resources/application-rds.yml

- 모든대화에 bookid, 도서제목, 대여상태, 이미지url, memerId 넣기,
- 채팅방목록에 이미지 url 넣기

Feat/be/채팅 api 수정

---

backend/src/main/java/com/dongnebook/domain/chat/application/ChatService.java
backend/src/main/java/com/dongnebook/domain/chat/application/RoomService.java
backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatResponse.java
backend/src/main/java/com/dongnebook/domain/chat/dto/response/ChatRoomResponse.java

Refactor : 채팅 내역 볼때 회원 추가

---

backend/build.gradle
backend/src/main/java/com/dongnebook/domain/chat/domain/RedisChat.java

[BE] Refactor : RedisChat LocalDateTime 역직렬화 문제 해결

---

backend/build.gradle
backend/src/main/java/com/dongnebook/domain/chat/Repository/ChatRepository.java
backend/src/main/java/com/dongnebook/domain/chat/domain/ChatRoom.java
backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
backend/src/main/java/com/dongnebook/global/config/security/auth/filter/TokenProvider.java
backend/src/main/resources/application-rds-createdb.yml
backend/src/main/resources/application-rds.yml
backend/src/main/resources/application.yml

-채팅방 최신순으로 오게 변경
-채팅방 목록에서 회원은 항상 상대방으로

[BE] Refactor : 채팅방 최신순으로 오게 변경, 채팅방 목록에서 회원은 항상 상대방으로

---

backend/src/main/java/com/dongnebook/domain/member/domain/Member.java
backend/src/main/java/com/dongnebook/domain/member/dto/response/BookDetailMemberResponse.java
backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberDetailResponse.java
backend/src/main/java/com/dongnebook/domain/review/application/ReviewService.java

- Review도메인: 리뷰 작성시, 상인 평균평점에 반영하는 로직 추가

[BE] Refactor: 리뷰 상인 평균평점 반영 로직 추가

---

backend/src/main/java/com/dongnebook/domain/book/dto/response/BookInfoResponse.java
backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
backend/src/main/java/com/dongnebook/domain/rental/domain/RentalState.java
backend/src/main/java/com/dongnebook/domain/rental/dto/request/RentalSearchCondition.java
backend/src/main/java/com/dongnebook/domain/rental/dto/response/RentalBookResponse.java
backend/src/main/java/com/dongnebook/domain/rental/dto/response/RentalInfoResponse.java
backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
backend/src/main/java/com/dongnebook/global/utils/Enum.java
backend/src/main/java/com/dongnebook/global/utils/EnumValidator.java

- Rental도메인: 대여목록(빌린 책, 빌려준 책) 조회시, 필터링 기능 추가
- Rental도메인: 대여목록(빌린 책, 빌려준 책) 조회시, 상인ID (merchantId) 포함해서 응답 데이터 제공

[BE] Feat: 대여목록(빌린책, 빌려준책) 조회시, 필터링 기능 추가

---

backend/src/main/java/com/dongnebook/DongnebookApplication.java
backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmService.java
backend/src/main/java/com/dongnebook/domain/book/application/BookService.java
backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
backend/src/main/java/com/dongnebook/domain/book/repository/BookQueryRepository.java
backend/src/main/java/com/dongnebook/domain/chat/application/ChatService.java
backend/src/main/java/com/dongnebook/domain/chat/ui/ChatController.java
backend/src/main/java/com/dongnebook/domain/rental/application/RentalCreateEvent.java
backend/src/main/java/com/dongnebook/domain/rental/application/RentalCreateEventHandler.java
backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
backend/src/main/java/com/dongnebook/domain/rental/domain/Rental.java
backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
backend/src/main/java/com/dongnebook/global/error/exception/ErrorCode.java
backend/src/main/java/com/dongnebook/global/test/BulkInsertController.java
backend/src/main/resources/application-test.yml
backend/src/test/java/com/dongnebook/DongnebookApplicationTests.java
backend/src/test/java/com/dongnebook/domain/rental/application/RentalServiceTest.java

- 채팅과 채팅시 오는 알람을 비동기로 처리되도록 바꿨습니다.
- 대여하기의 동시성 문제를 해결하였습니다.

Feat : 채팅보낼때 알람은 비동기로, 대여하기 동시성 제어

---

backend/src/main/java/com/dongnebook/DongnebookApplication.java
backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmQueryRepository.java
backend/src/main/java/com/dongnebook/domain/alarm/domain/AlarmService.java
backend/src/main/java/com/dongnebook/domain/alarm/ui/AlarmController.java
backend/src/main/java/com/dongnebook/domain/chat/domain/ChatRoom.java
backend/src/main/java/com/dongnebook/domain/rental/application/RentalService.java
backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
backend/src/main/java/com/dongnebook/domain/rental/ui/RentalController.java
backend/src/main/resources/application-rds-createdb.yml
backend/src/main/resources/application-rds.yml
backend/src/main/resources/application-test.yml
backend/src/main/resources/application.yml
backend/src/test/java/com/dongnebook/domain/rental/application/RentalServiceTest.java

- 알림 전체 삭제 기능
- 매일 1시에 반납하루남은 사람에게 알람 가는 기능
- 배치사이즈 옵션 추가

[BE] Feat : 알람 전체 삭제 기능, 반납 대여 알림

---

backend/src/main/java/com/dongnebook/domain/member/repository/MemberQueryRepository.java

[BE] Refactor : 등록한 도서수 삭제된거는 제외되도록 수정

---

backend/build.gradle
backend/src/main/java/com/dongnebook/domain/book/domain/Book.java
backend/src/main/java/com/dongnebook/domain/member/application/MemberService.java
backend/src/main/java/com/dongnebook/domain/member/dto/request/MerchantSearchRequest.java
backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberDetailResponse.java
backend/src/main/java/com/dongnebook/domain/member/dto/response/MemberResponse.java
backend/src/main/java/com/dongnebook/domain/member/exception/MemberHasOnLoanException.java
backend/src/main/java/com/dongnebook/domain/member/ui/MemberController.java
backend/src/main/java/com/dongnebook/domain/rental/repository/RentalQueryRepository.java
backend/src/main/java/com/dongnebook/global/security/auth/filter/JwtAuthenticationFilter.java
backend/src/main/java/com/dongnebook/global/security/auth/filter/JwtVerificationFilter.java
backend/src/main/java/com/dongnebook/global/security/auth/filter/TokenProvider.java
backend/src/test/java/com/dongnebook/domain/book/repository/BookQueryRepositoryTest.java
backend/src/test/java/com/dongnebook/domain/member/application/MemberServiceTest.java
backend/src/test/java/com/dongnebook/support/BookStub.java
backend/src/test/java/com/dongnebook/support/MemberStub.java

- MemberService의 단위 테스트를 추가하였습니다.
- 액세스토큰 재발급 로직을 수정하였습니다.
- 토큰에 권한정보를 담던걸 걷어냈습니다.

[BE] Test: MemberService 단위 테스트

---

backend/src/main/java/com/dongnebook/domain/model/image/application/ImageUploadService.java
backend/src/main/java/com/dongnebook/domain/model/image/infrastructure/AwsS3Service.java
backend/src/main/java/com/dongnebook/domain/model/image/ui/ImageUploadController.java

[BE] Feat : 이미지 리사이징
